apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: java-app-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: java-app-deploy # 监控的目标 Deployment
    minReplicas: 2 # 最小副本数
    maxReplicas: 10 # 最大副本数
    targetCPUUtilizationPercentage: 50 # 目标 CPU 使用率
