apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-init-scripts
data:
    init.sql: |
        CREATE TABLE IF NOT EXISTS orders (
          id INT AUTO_INCREMENT PRIMARY KEY,
          user_id INT NOT NULL,
          order_no VARCHAR(50) NOT NULL,
          amount DECIMAL(10,2),
          status TINYINT,
          create_time DATETIME,
          note VARCHAR(500),
          KEY idx_user (user_id)
        ) ENGINE=InnoDB;

        -- 2. 创建造数存储过程
        DELIMITER $$
        DROP PROCEDURE IF EXISTS insert_data_k8s $$
        CREATE PROCEDURE insert_data_k8s(IN total INT)
        BEGIN
          DECLARE i INT DEFAULT 0;
          SET autocommit = 0;
          WHILE i < total DO
            INSERT INTO orders (user_id, order_no, amount, status, create_time, note)
            VALUES (
              FLOOR(1 + RAND() * 1000),
              UUID(),
              ROUND(RAND() * 1000, 2),
              1,
              NOW(),
              REPEAT('K8s Performance Test! ', 10)
            );
            SET i = i + 1;
            IF MOD(i, 1000) = 0 THEN COMMIT; END IF;
          END WHILE;
          COMMIT;
          SET autocommit = 1;
        END$$
        DELIMITER ;
